### ISSUE TITLE
下午更新的，会发两次消息，是bug吧

### ISSUE THREAD

**Issue by wqzai** [chinosk114514/QQ-official-guild-bot#1]

**Comment by wqzai** [comment]
![Screenshot_2021-12-05-23-57-07-232_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/81562515/144753819-7a30c145-9d48-49e4-89ee-326640e32a71.jpg)

**Comment by chinosk6** [comment]
是使用的http还是直接用的sdk呢

**Comment by wqzai** [comment]
> 是使用的http还是直接用的sdk呢

直接SDK，然后我又换昨天的版本，又是正常的

**Comment by chinosk6** [comment]
> > 是使用的http还是直接用的sdk呢
> 
> 直接SDK，然后我又换昨天的版本，又是正常的

刚才测试了一下, 没有重现这个问题。请问您具体是怎么调用的呢
![image](https://user-images.githubusercontent.com/74499927/144754249-5fd0d9d4-51ad-473b-8849-0143e6605f64.png)

**Comment by wqzai** [comment]
> > > 是使用的http还是直接用的sdk呢
> > 
> > 直接SDK，然后我又换昨天的版本，又是正常的
> 
> 刚才测试了一下, 没有重现这个问题。请问您具体是怎么调用的呢
> ![image](https://user-images.githubusercontent.com/74499927/144754249-5fd0d9d4-51ad-473b-8849-0143e6605f64.png)
> 

我现在也正常了，但是刚才真的出现了😭，打扰了，感谢大佬！！

**Comment by chinosk6** [comment]
没事没事。突然发现我们在一个群，有问题的话也可以直接找我~
