### ISSUE TITLE
设置指定子频道回复消息

### ISSUE THREAD

**Issue by rainbowwarmth** [chinosk114514/QQ-official-guild-bot#16]
能不能写一个消息设置指定子频道才能回复消息的一段代码

**Comment by wqzai** [comment]
当然可以，简单的操作就：直接if判断一下当前触发指令的子判断id是不是指定的子频道id，是就按计划回复，不是就指引到正确子频道就行

**Comment by wqzai** [comment]
> 能不能写一个消息设置指定子频道才能回复消息的一段代码

当然可以，简单的操作就：直接if判断一下当前触发指令的子频道id是不是指定的子频道id，是就按计划回复，不是就指引到正确子频道就行
