### ISSUE TITLE
ark消息支持

### ISSUE THREAD

**Issue by wqzai** [chinosk114514/QQ-official-guild-bot#2]
希望增加ark消息支持

**Comment by chinosk6** [comment]
主要是我这边没有ark消息权限，没办法测试。不过我可以直接在`api_send_reply_message`里添加一个ark的参数，json由您自己构建

**Comment by wqzai** [comment]
很抱歉我不懂🌚🌚，要不然我也想自己写😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月10日(周五) 中午11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinosk114514/QQ-official-guild-bot] ark消息支持 (Issue #2)




 
主要是我这边没有ark消息权限，没办法测试。不过我可以直接在api_send_reply_message里添加一个ark的参数，json由您自己构建

**Comment by chinosk6** [comment]
> 很抱歉我不懂🌚🌚，要不然我也想自己写😂
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年12月10日(周五) 中午11:10 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [chinosk114514/QQ-official-guild-bot] ark消息支持 (Issue #2) 主要是我这边没有ark消息权限，没办法测试。不过我可以直接在api_send_reply_message里添加一个ark的参数，json由您自己构建 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

那我尝试写一写，到时候可能需要麻烦您测试下

**Comment by wqzai** [comment]
好的，我几乎是个小白，到时候具体怎么用？能放个demo进去吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月10日(周五) 中午11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinosk114514/QQ-official-guild-bot] ark消息支持 (Issue #2)




  
很抱歉我不懂🌚🌚，要不然我也想自己写😂
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年12月10日(周五) 中午11:10 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [chinosk114514/QQ-official-guild-bot] ark消息支持 (Issue #2) 主要是我这边没有ark消息权限，没办法测试。不过我可以直接在api_send_reply_message里添加一个ark的参数，json由您自己构建 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
那我尝试写一写，到时候可能需要麻烦您测试下

**Comment by chinosk6** [comment]
> 好的，我几乎是个小白，到时候具体怎么用？能放个demo进去吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年12月10日(周五) 中午11:30 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [chinosk114514/QQ-official-guild-bot] ark消息支持 (Issue #2) 很抱歉我不懂🌚🌚，要不然我也想自己写😂 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年12月10日(周五) 中午11:10 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [chinosk114514/QQ-official-guild-bot] ark消息支持 (Issue #2) 主要是我这边没有ark消息权限，没办法测试。不过我可以直接在api_send_reply_message里添加一个ark的参数，json由您自己构建 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 那我尝试写一写，到时候可能需要麻烦您测试下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

肯定是有文档的

**Comment by chinosk6** [comment]
已更新`Ark`支持

**Comment by wqzai** [comment]
好的，感谢大佬😍



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月10日(周五) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinosk114514/QQ-official-guild-bot] ark消息支持 (Issue #2)




 
已更新Ark支持
