### ISSUE TITLE
功能反馈

### ISSUE THREAD

**Issue by SaucePlum** [chinosk114514/QQ-official-guild-bot#3]
想知道怎么切换正式环境

**Comment by chinosk6** [comment]
初始化Bot类时, 有一个 `is_sandbox` 的参数, 设置为`False`即可

**Comment by SaucePlum** [comment]
默认值是布尔的那个吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月10日(周四) 晚上7:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinosk114514/QQ-official-guild-bot] 功能反馈 (Issue #3)




 
初始化Bot类时, 有一个 is_sandbox 的参数, 设置为False即可
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chinosk6** [comment]
> 默认值是布尔的那个吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年2月10日(周四) 晚上7:05 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [chinosk114514/QQ-official-guild-bot] 功能反馈 (Issue #3) 初始化Bot类时, 有一个 is_sandbox 的参数, 设置为False即可 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

对
![image](https://user-images.githubusercontent.com/74499927/153395103-351c957f-4f39-42e2-a155-f503fdc91795.png)

**Comment by SaucePlum** [comment]
我把api文件的改成了False测试之后是沙箱环境&nbsp; &nbsp;然后又改了sdk_main，还是在沙箱环境&nbsp; &nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chinosk114514/QQ-official-guild-bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 晚上7:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chinosk114514/QQ-official-guild-bot] 功能反馈 (Issue #3)





  
默认值是布尔的那个吗？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年2月10日(周四) 晚上7:05 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [chinosk114514/QQ-official-guild-bot] 功能反馈 (Issue #3) 初始化Bot类时, 有一个 is_sandbox 的参数, 设置为False即可 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
对
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chinosk6** [comment]
> 我把api文件的改成了False测试之后是沙箱环境&nbsp; &nbsp;然后又改了sdk_main，还是在沙箱环境&nbsp; &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "chinosk114514/QQ-official-guild-bot" ***@***.***&gt;; 发送时间:&nbsp;2022年2月10日(星期四) 晚上7:09 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [chinosk114514/QQ-official-guild-bot] 功能反馈 (Issue #3) 默认值是布尔的那个吗？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年2月10日(周四) 晚上7:05 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [chinosk114514/QQ-official-guild-bot] 功能反馈 (Issue #3) 初始化Bot类时, 有一个 is_sandbox 的参数, 设置为False即可 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt; 对 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

?不需要改动sdk源码, 只用在初始化类的时候, `is_sandbox`参数值填`False`即可

**Comment by SaucePlum** [comment]
了解&nbsp; 小生愚笨 感谢大哥指教




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chinosk114514/QQ-official-guild-bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chinosk114514/QQ-official-guild-bot] 功能反馈 (Issue #3)





  
我把api文件的改成了False测试之后是沙箱环境&nbsp; &nbsp;然后又改了sdk_main，还是在沙箱环境&nbsp; &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "chinosk114514/QQ-official-guild-bot" @.&gt;; 发送时间:&nbsp;2022年2月10日(星期四) 晚上7:09 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [chinosk114514/QQ-official-guild-bot] 功能反馈 (Issue #3) 默认值是布尔的那个吗？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年2月10日(周四) 晚上7:05 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [chinosk114514/QQ-official-guild-bot] 功能反馈 (Issue #3) 初始化Bot类时, 有一个 is_sandbox 的参数, 设置为False即可 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 对 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
  
?不需要改动sdk源码, 只用在初始化类的时候, 第is_sandbox参数值填False即可
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
