### ISSUE TITLE
连接断开问题

### ISSUE THREAD

**Issue by SaucePlum** [chinosk114514/QQ-official-guild-bot#4]
在服务器端 重启项目之后一直是连接断开的详细如图
![image](https://user-images.githubusercontent.com/48905684/154678258-48505bb0-714c-47d1-a38b-7085674f8015.png)

**Comment by chinosk6** [comment]
你是不是启动了两次Bot

**Comment by chinosk6** [comment]
一次运行只能实例化一个BotAPP

**Comment by SaucePlum** [comment]
没有啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月18日(周五) 晚上7:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinosk114514/QQ-official-guild-bot] 连接断开问题 (Issue #4)




 
你是不是启动了两次Bot
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chinosk6** [comment]
> 没有啊
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年2月18日(周五) 晚上7:59 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [chinosk114514/QQ-official-guild-bot] 连接断开问题 (Issue #4) 你是不是启动了两次Bot — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

代码看看

**Comment by SaucePlum** [comment]
已经修复了，谢谢啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月18日(周五) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinosk114514/QQ-official-guild-bot] 连接断开问题 (Issue #4)




  
没有啊
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年2月18日(周五) 晚上7:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [chinosk114514/QQ-official-guild-bot] 连接断开问题 (Issue #4) 你是不是启动了两次Bot — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
代码看看
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
