### ISSUE TITLE
关于Embed消息的问题

### ISSUE THREAD

**Issue by SaucePlum** [chinosk114514/QQ-official-guild-bot#5]
刚刚官方直播间问过了  Embed是不需要申请ark权限的  可以直接发送
所以刚刚测试了一下  发现有误
![image](https://user-images.githubusercontent.com/48905684/154687323-410ed81e-9bd1-43dc-9fef-f7d8a1ae65b5.png)

**Comment by chinosk6** [comment]
测试后并没有复现同样的问题, 请再次确认出错的位置~

**Comment by chinosk6** [comment]
如果还有相同的问题, 请Reopen这个issue~
