### ISSUE TITLE
emoji表情发送

### ISSUE THREAD

**Issue by SaucePlum** [chinosk114514/QQ-official-guild-bot#6]
![image](https://user-images.githubusercontent.com/48905684/154831544-3ad82a78-e50c-4755-9a80-5739ffecd43a.png)

想知道emoji表情怎么发送，有没有具体的代码示例

**Comment by chinosk6** [comment]
你的截图里面是表情表态对象使用的参数, 要发送的话可以直接输入emoji
![image](https://user-images.githubusercontent.com/74499927/154832284-009c258b-a4ad-427f-abbc-e0fee2fa5ca2.png)

**Comment by SaucePlum** [comment]
有详细发送消息的示例给一个嘛



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月20日(周日) 下午3:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinosk114514/QQ-official-guild-bot] emoji表情发送 (Issue #6)




 
你的截图里面是表情表态对象使用的参数, 要发送的话可以直接输入emoji
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chinosk6** [comment]
直接当成字符串处理
![image](https://user-images.githubusercontent.com/74499927/154832417-eee1461e-c052-480c-a0d4-9c851669fe7a.png)

**Comment by SaucePlum** [comment]
pycharm里面emoji很多不识别



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月20日(周日) 下午3:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinosk114514/QQ-official-guild-bot] emoji表情发送 (Issue #6)




 
直接当成字符串处理
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chinosk6** [comment]
pycharm不显示不代表不能发吧...如果有不能发的emoji, 麻烦您发来看看~

**Comment by SaucePlum** [comment]
🏆🥇🥈🥉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月20日(周日) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinosk114514/QQ-official-guild-bot] emoji表情发送 (Issue #6)




 
pycharm不显示不代表不能发吧...如果有不能发的emoji, 麻烦您发来看看~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chinosk6** [comment]
![image](https://user-images.githubusercontent.com/74499927/154832896-65176a26-988b-4be4-9b28-03e7b233e669.png)
![image](https://user-images.githubusercontent.com/74499927/154832906-d0a12a27-2638-48af-ad08-92e56efb1b5b.png)
是可以发的

**Comment by SaucePlum** [comment]
用的pycharm？字体？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月20日(周日) 下午3:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chinosk114514/QQ-official-guild-bot] emoji表情发送 (Issue #6)




 

 
 是可以发的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chinosk6** [comment]
发送和字体没关系。我用的就是默认字体, `JetBrains Mono`。
