### ISSUE TITLE
好像FUNC_CALL_AFTER_BOT_LOAD事件在设置为false，重连后还是会重复触发

### ISSUE THREAD

**Issue by wqzai** [chinosk114514/QQ-official-guild-bot#7]
![MTXO5T)ZL_Z}%51`~M{WY~Y](https://user-images.githubusercontent.com/81562515/155643871-cba3759a-b5aa-4655-ad28-63ff7f106857.png)
![R8L(X(AIMK82SBO%ZN$1SEQ](https://user-images.githubusercontent.com/81562515/155643939-f81f9bb4-f09a-4b34-8222-9118f43cca09.png)
![F9IWNC@87 Q(39BSRE39{ET](https://user-images.githubusercontent.com/81562515/155643952-6a8739c6-9f8a-4ec7-99b8-ad60062cd719.png)
![@A8NELSSIEIJZE2CRFKV2VA](https://user-images.githubusercontent.com/81562515/155643965-771e5a5c-d9c7-42af-9a32-192fd2e6019f.png)

**Comment by chinosk6** [comment]
已修复~
